# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design System
baseurl: " " # the subpath of your site, e.g. /blog
url: "https://idlt-design-system.github.io/" # the base hostname & protocol for your site
remote_theme: lundegaard/design-system-template

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Setup pattern collection
collections:
  patterns:
    output: true

# Overriding default colors
branding:
  logo_path: '/assets/logo.svg'
  navigation_background_color: '#eee'
  navigation_link_color: '#444'
  navigation_link_color_hover: 'gray'
  main_background_color: '#fff'
  highlight_color: '#444'
  code_background_color: '#f9f9f9'
  
# GTM analytics
gtm_id: GTM-XXXXXX